# Generated by Django 5.0.2 on 2024-02-19 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0002_remove_login_is_admin_collegeadmin_user_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Science', models.CharField(max_length=30)),
                ('Maths', models.CharField(max_length=30)),
                ('Physics', models.CharField(max_length=30)),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.student')),
            ],
        ),
    ]
